'use client'

import { PageMetadata } from '@/types/wiki'
import { formatDistanceToNow } from 'date-fns'
import { Eye, Clock, Calendar, Award, BookOpen } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'

interface Props {
  title: string
  metadata: PageMetadata
  confidence: number
  viewCount: number
  generatedAt: string
}

/**
 * Confidence badge with color coding
 */
function ConfidenceBadge({ score }: { score: number }) {
  const level = score > 0.8 ? 'high' : score > 0.6 ? 'medium' : 'low'

  const config = {
    high: {
      label: 'Well-sourced',
      className: 'bg-green-100 text-green-800 hover:bg-green-200 dark:bg-green-900/30 dark:text-green-400',
      description: 'This page is based on comprehensive, high-quality sources.',
    },
    medium: {
      label: 'Moderately sourced',
      className: 'bg-yellow-100 text-yellow-800 hover:bg-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-400',
      description: 'This page is based on available sources with moderate coverage.',
    },
    low: {
      label: 'Limited sources',
      className: 'bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-400',
      description: 'This page has limited source material available.',
    },
  }[level]

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge className={config.className}>
            <Award className="h-3 w-3 mr-1" aria-hidden="true" />
            {config.label}
          </Badge>
        </TooltipTrigger>
        <TooltipContent className="max-w-xs">
          <p>{config.description}</p>
          <p className="text-xs text-muted-foreground mt-1">
            Confidence score: {(score * 100).toFixed(0)}%
          </p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

/**
 * Estimate reading time from content
 */
function estimateReadingTime(content: string): number {
  const wordsPerMinute = 200
  const wordCount = content.split(/\s+/).length
  return Math.ceil(wordCount / wordsPerMinute)
}

/**
 * Page header component with title and metadata
 * Includes: confidence badge, view count, reading time, last updated
 */
export function PageHeader({
  title,
  metadata,
  confidence,
  viewCount,
  generatedAt,
}: Props) {
  const chunkCount = metadata.chunk_count || metadata.sources_used?.length || 0
  const readingTime = metadata.description
    ? estimateReadingTime(metadata.description)
    : 5

  return (
    <header className="wiki-page-header border-b border-border bg-gradient-to-b from-almanac-cream-50 to-transparent dark:from-gray-900/20">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="font-serif text-4xl md:text-5xl font-bold text-almanac-earth-800 dark:text-almanac-earth-200 mb-4">
            {title}
          </h1>

          {/* Metadata bar */}
          <div className="flex flex-wrap gap-3 items-center text-sm text-almanac-earth-600 dark:text-almanac-earth-400">
            <ConfidenceBadge score={confidence} />

            <span className="text-border" aria-hidden="true">
              •
            </span>

            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger className="flex items-center gap-1.5 hover:text-almanac-sage-700 dark:hover:text-almanac-sage-400 transition-colors">
                  <BookOpen className="h-4 w-4" aria-hidden="true" />
                  <span>{chunkCount} sources consulted</span>
                </TooltipTrigger>
                <TooltipContent>
                  <p>
                    This page was generated by analyzing {chunkCount} excerpts from source
                    documents
                  </p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>

            <span className="text-border" aria-hidden="true">
              •
            </span>

            <div className="flex items-center gap-1.5">
              <Calendar className="h-4 w-4" aria-hidden="true" />
              <span>Updated {formatDistanceToNow(new Date(generatedAt), { addSuffix: true })}</span>
            </div>

            {viewCount > 0 && (
              <>
                <span className="text-border" aria-hidden="true">
                  •
                </span>
                <div className="flex items-center gap-1.5">
                  <Eye className="h-4 w-4" aria-hidden="true" />
                  <span>{viewCount.toLocaleString()} views</span>
                </div>
              </>
            )}

            <span className="text-border" aria-hidden="true">
              •
            </span>

            <div className="flex items-center gap-1.5">
              <Clock className="h-4 w-4" aria-hidden="true" />
              <span>{readingTime} min read</span>
            </div>
          </div>

          {/* Description/excerpt if available */}
          {metadata.description && (
            <p className="mt-4 text-lg text-muted-foreground leading-relaxed">
              {metadata.description}
            </p>
          )}
        </div>
      </div>
    </header>
  )
}
